{% set name = "htbuilder" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/htbuilder-{{ version }}.tar.gz
  sha256: 61435d649438d5b7c3d30868f5644b83f0ab488d411eb0485439cb9e05223f19

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - more-itertools
    - python >=3.5

test:
  imports:
    - htbuilder
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tvst/htbuilder
  summary: A purely-functional HTML builder for Python. Think JSX rather than templates.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
